### ISSUE TITLE
Контакты

### ISSUE THREAD

**Issue by monerorus** [SChernykh/CryptonightR#6]
Приветствую.
Не могли бы вы сообщить способы связи для общения? Как и где вас найти? Телеграм, реддит, IRC, почта, что-нибудь? 
Не смог обнаружить других вариантов поэтому использую такой вот вариант связи :)

**Comment by SChernykh** [comment]
https://www.reddit.com/user/sech1
Discord: sech1#3141
IRC: sech1 в #monero-pools, #monero-dev, #monero-pow на freenode

**Comment by monerorus** [comment]
Спасибо
